<?php

namespace DarkGhostHunter\Larakick\Generation\Gates;

use Illuminate\Contracts\Auth\Access\Gate;

trait RegistersGates
{
    /**
     * Register Gates.
     *
     * @return void
     */
    protected function registerGates()
    {
        $gates = $this->gates();

        if (property_exists($this, 'gates')) {
            $gates = array_merge($this->gates);
        }

        if (empty($gates)) {
            return;
        }

        $gate = $this->app->make(Gate::class);

        foreach ($gates as $name => $callable) {
            $gate->define($name, $callable);
        }
    }

    /**
     * Autogenerated array of Gates to register.
     *
     * @return array
     */
    protected function gates()
    {
        return [];
    }
}
